services:
  testetoradex:
    user: root
    privileged: true
    image: gabigoltupa/tx:tx0.2v
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /datalogger
        target: /datalogger
      - type: bind
        source: /processed_data
        target: /processed_data
      - shared-data:/shared
    cap_add:
      - CAP_NET_ADMIN
    network_mode: host
    device_cgroup_rules:
      - "c 4:0 rmw"
      - "c 4:7 rmw"
      - "c 13:* rmw"
      - "c 199:* rmw"
      - "c 226:* rmw"
    depends_on:
      - weston

  weston:
    user: root
    privileged: true
    image: torizon/weston-imx8:4
    environment:
      - ACCEPT_FSL_EULA=1
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev


  telemetry:
    build: ./telemetry
    container_name: telemetry
    network_mode: host

    volumes:
      - ./telemetry:/app
      - ./logs:/logs

    depends_on:
      - acquisition
    restart: unless-stopped



#  imu:
#    build: ./imu
#    container_name: imu
#    privileged: true
#    devices:
#      - /dev/i2c-3:/dev/i2c-3   # (change to your real bus)
#    volumes:
#      - shared-data:/shared
#      - ./imu:/app
#    working_dir: /app
#    command: python3 bno055.py
#    restart: unless-stopped

  acquisition:
    build: ./Acquisition
    container_name: acquisition_gateway

    # Required for CAN + I2C hardware access
    privileged: true

    # Allow direct access to CAN network stack
    network_mode: host

    # I2C device passthrough
    devices:
      - "/dev/i2c-3:/dev/i2c-3"
    command: python3 main.py
    restart: unless-stopped


#  usb-transfer:
#    user: root
#    privileged: true
#    image: kapukakec2/t09:t09Data
#    volumes:
#      - type: bind
#        source: /datalogger
#        target: /datalogger
#      - type: bind
#        source: /var/rootdirs/media/EE8D-F793
#        target: /var/rootdirs/media/EE8D-F793
#    restart: "no"


volumes:
  shared-data:
