version: "3.9"

services:

  testetoradex:
    user: root
    privileged: true
    image: gabigoltupa/tx:tx0.2v
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /datalogger
        target: /datalogger
      - type: bind
        source: /processed_data
        target: /processed_data
      - shared-data:/shared
    cap_add:
      - CAP_NET_ADMIN
    network_mode: host
    device_cgroup_rules:
      - "c 4:0 rmw"
      - "c 4:7 rmw"
      - "c 13:* rmw"
      - "c 199:* rmw"
      - "c 226:* rmw"
    depends_on:
      - weston

  weston:
    user: root
    privileged: true
    image: torizon/weston-imx8:4
    environment:
      - ACCEPT_FSL_EULA=1
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev

  acquisition:
    build: ./Acquisition
    container_name: acquisition
    privileged: true
    network_mode: host
    devices:
      - "/dev/i2c-3:/dev/i2c-3"
      - "/dev/ttymxc1:/dev/ttymxc1"
    command: python3 main.py
    restart: unless-stopped

  control:
    build: ./Control
    container_name: control
    network_mode: host
    command: python3 control.py
    restart: unless-stopped
    depends_on:
      - acquisition

  telemetry:
    build: ./telemetry
    container_name: telemetry
    network_mode: host
    volumes:
      - ./telemetry:/app
      - ./logs:/logs
    command: python3 telemetry.py
    depends_on:
      - control
    restart: unless-stopped

volumes:
  shared-data:
